In [1]:
import tensorflow as tf


In [2]:
# create a tensor

tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [3]:
#scalar

tf.constant(42) 

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [4]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

t.shape

TensorShape([2, 3])

In [7]:
# matrix multiplication

t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

# Tensors and Numpy

In [8]:
# adding with different dtypes use -> cast

t2 = tf.constant(40., dtype=tf.float64)
tf.constant(2.0) + tf.cast(t2, tf.float32)


<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

# Variables

Values that can be changed. For example weights in a neural network; constants are fixed

In [9]:
v = tf.Variable([[1., 2., 3.], [4., 5., 6.]])


In [10]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,   2.,   3.],
       [  4.,   5., 200.]], dtype=float32)>

In [11]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[100.,   2.,   3.],
       [  4.,   5., 200.]], dtype=float32)>